Get data rapt
LucasPerrault/RatpProjectAdvance pull request #1
Opened 2019-12-05 15:24 UTC by LucasPerrault

Ajout d'une classe HttpUrlConnection qui prend l'url en question et effectue un get dessus. 
La méthode renvoie les données stringifiées.

2019-12-06 13:51 UTC, bastiengrignon requested changes
Seems good but why the user agent is **Mozzilla 5** ? What happen if i change to another **user agent** ?
I don't think "sendGET" method is a good name, it's contradictory

2019-12-19 08:20 UTC, LucasPerrault commented
> Seems good but why the user agent is **Mozzilla 5** ? What happen if i change to another **user agent** ?
> I don't think "sendGET" method is a good name, it's contradictory

2019-12-19 11:05 UTC, bastiengrignon approved these changes

2019-12-19 11:05 UTC, bastiengrignon commented on src/main.java
>  public class main {
main need to be changed in another review

2019-12-19 11:07 UTC, merged